# Generated by Django 5.1.3 on 2024-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAdministrativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_admin', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.CharField(max_length=40)),
                ('patente', models.CharField(max_length=40)),
                ('apellido_nombre_admin', models.CharField(max_length=40)),
                ('observaciones', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateTimeField(auto_now_add=True)),
                ('chofer', models.CharField(max_length=40)),
                ('dni_camion', models.CharField(max_length=40)),
                ('transporte', models.CharField(max_length=40)),
                ('tractor', models.CharField(max_length=40)),
                ('semi', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='registrovehiculo',
            old_name='chofer_dni',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='registrovehiculo',
            old_name='fecha_ingreso',
            new_name='entrada',
        ),
        migrations.RenameField(
            model_name='registrovehiculo',
            old_name='patente_tractor',
            new_name='pte_nro',
        ),
        migrations.RemoveField(
            model_name='registrovehiculo',
            name='bultos_egreso',
        ),
        migrations.RemoveField(
            model_name='registrovehiculo',
            name='bultos_ingreso',
        ),
        migrations.RemoveField(
            model_name='registrovehiculo',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='registrovehiculo',
            name='remito_egreso',
        ),
        migrations.RemoveField(
            model_name='registrovehiculo',
            name='remito_ingreso',
        ),
        migrations.RemoveField(
            model_name='registrovehiculo',
            name='transporte',
        ),
        migrations.AddField(
            model_name='registrovehiculo',
            name='apellido_nombre',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='registrovehiculo',
            name='empresa',
            field=models.CharField(default='Sin nombre', max_length=40),
        ),
        migrations.AddField(
            model_name='registrovehiculo',
            name='ingreso_remitos',
            field=models.CharField(default='Sin nombre', max_length=40),
        ),
    ]
