# Generated by Django 5.1.3 on 2024-12-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_registroadministrativos_registrocamion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroadministrativos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
