# Generated by Django 5.1.3 on 2024-12-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_registroadministrativos_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovehiculo',
            name='patente_semi',
        ),
        migrations.AddField(
            model_name='registrovehiculo',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

