# Generated by Django 5.1.3 on 2024-12-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_registrovehiculo_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovehiculo',
            name='apellido_nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='empresa',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='ingreso_remitos',
            field=models.CharField(max_length=40),
        ),
    ]
