# Generated by Django 5.1.3 on 2024-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_remove_registrocamion_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroadministrativos',
            name='entrada_admin',
        ),
        migrations.RemoveField(
            model_name='registrovehiculo',
            name='pte_nro',
        ),
        migrations.AddField(
            model_name='registroadministrativos',
            name='entrada_admin1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrovehiculo',
            name='pte_numero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrovehiculo',
            name='salida_vehiculo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrocamion',
            name='ingreso_camion1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='apellido_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='ingreso_remitos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
