# Generated by Django 5.1.3 on 2024-12-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_remove_registroadministrativos_entrada_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroadministrativos',
            name='entrada_admin1',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
