# Generated by Django 5.1.3 on 2024-12-12 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_alter_registroadministrativos_entrada_admin1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroadministrativos',
            name='entrada_admin1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registrocamion',
            name='ingreso_camion1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
