# Generated by Django 5.1.3 on 2024-12-23 15:28

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_alter_registroadministrativos_apellido_nombre_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovehiculo',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='registrovehiculo',
            name='egreso_remitos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='dni',
            field=models.CharField(default='00000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='entrada',
            field=models.DateTimeField(default=now),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='ingreso_remitos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='pte_numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='salida_vehiculo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
