# Generated by Django 5.1.3 on 2024-12-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_remove_registrovehiculo_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovehiculo',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='entrada',
            field=models.DateTimeField(),
        ),
    ]
