# Generated by Django 5.1.3 on 2024-12-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_remove_registrocamion_dni_camion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroCamion',
            new_name='RegistroCamiones',
        ),
    ]
