# Generated by Django 5.1.3 on 2025-01-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0018_alter_registroadministrativos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocamiones',
            name='egreso2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrocamiones',
            name='egreso3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrocamiones',
            name='ingreso2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrocamiones',
            name='ingreso3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='salida_vehiculo',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
