# Generated by Django 5.1.3 on 2025-01-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0020_alter_registrocamiones_chofer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocamiones',
            name='egreso2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrocamiones',
            name='egreso3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrocamiones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrocamiones',
            name='ingreso2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrocamiones',
            name='ingreso3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
