# Generated by Django 5.1.3 on 2025-01-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0021_alter_registrocamiones_egreso2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocamiones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
