# Generated by Django 5.1.3 on 2025-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0022_alter_registrocamiones_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocamiones',
            name='egreso2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrocamiones',
            name='egreso3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrocamiones',
            name='ingreso',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registrocamiones',
            name='ingreso2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrocamiones',
            name='ingreso3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
